language: emacs-lisp

env:
  matrix:
    - EMACS=emacs-snapshot

install:
  sudo add-apt-repository -y ppa:ubuntu-elisp/ppa &&
  sudo apt-get update -qq &&
  sudo apt-get install -qq emacs-snapshot;

script:
  make test EMACS=${EMACS}
